dubbo:
  application:
    name: b2c-search-service
  registry:
    address: zookeeper://192.168.56.88:2181
  protocol:
    name: dubbo
    port: 20883

spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.56.88:3306/b2c?serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: M+NNa+0EXyTY8NUm1Wo8+URJTsRokNLTCPb2fVL+k9RQpuIluFQ/eyrH4P8ARNWbOjRuYSRi9OI+RY+d0rh4QA==
      filters: config
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJI7JbABj5q4T0cF4xoeYtkimXRDeRruhsElYPzEgYyP6YXpRlGkFK52AIQUv6E8ZjfkcsnRjabOOXlhTytPHJMCAwEAAQ==
      initial-size: 1
      max-active: 20
      max-wait: 10000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      validation-query: select 1

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        url-pattern: /druid/*

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  main:
    allow-circular-references: true
  redis:
    host: 192.168.56.88
    port: 6379
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.56.88:9300

mybatis:
  type-aliases-package: com.turing.b2c.model.pojo
  mapper-locations: classpath:/com/turing/b2c/mapper/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    lazy-load-trigger-methods:
    - ""
    map-underscore-to-camel-case: true

logging:
  level:
    com.turing.b2c.mapper: debug

